In [2]:
from chython import smarts
from chython.exceptions import IncorrectSmiles

from tqdm.auto import tqdm

In [ ]:
# pathw to the rule files that extracted under same configuration
tsv_path_a = "../mapping/uspto_full_rules_light_pop_3_uu.tsv"
tsv_path_b = "../mapping/uspto_full_rules_light_pop_3_uuu.tsv"

In [6]:
def load_rules(tsv_path):
    data_q = []
    errors = []
    with open(tsv_path, encoding="utf-8") as f:
        f.readline()  # skip header
        for line in tqdm(f):
            line = line.rstrip("\n")
            if not line:
                continue
            try:
                rule_smarts = line.split("\t", 1)[0]
                q = smarts(rule_smarts)
                cq = ~q
                data_q.append((q, cq))
            except IncorrectSmiles:
                errors.append(rule_smarts)
    return data_q, errors

In [7]:
a_q, errors_a = load_rules(tsv_path_a)

0it [00:00, ?it/s]

In [8]:
b_q, errors_b = load_rules(tsv_path_b)

0it [00:00, ?it/s]

In [5]:
difference_ab = list(set([cq for _, cq in a_q]) - set([cq for _, cq in b_q]))
print(len(difference_ab))
for r in difference_ab:
    r.clean2d()
    display(r)
    print(str(r))

11

[O;1>1;][.>-][C;3>4;]1([C;3>3;])[C;3>3;]:[C;3>3;][C;3>3;]([C;3>3;])[->=][C;3>3;]1[C;3>3;][O;1>2;][.>-][C;2>2;][C;1>1;]

[Cl;1>1;][.>-][C;3>3;]1([->.][N;3>2;]([C;3>3;]:[C;3>3;][N;3>2;]([C;2>2;])[->.][C;3>3;]([.>-][Cl;1>1;])([C;3>3;]1)=[O;1>1;])[C;3>3;])=[O;1>1;]

[O;1>1;][.>=][C;3>3;][:>.]1([C;3>3;])[:>-][C;2>1;][:>.][C;3>3;]([.>-][O;2>2;][C;2>2;][C])([.>=][O;1>1;])([C;3>3;])[:>.][N;2>1;][:>-][N;2>1;][:>.]1

[O;2>2;]([C;3>3;]:1:[C]:[C]:[C]([N+]([O-])=[O]):[C]:[C]:1)[.>-][C;3>3;]([->.][O;2>1;][C;3>3;])(=[O;1>1;])[O;2>2;]

[F;1>1;][.>-][C;3>3;]([->.][N;3>3;]12[.>-][C;3>3;](:[C;2>2;])(:[C;2>2;])[->.][N;3>2;]([C;2>2;][C;2>2;]1)[C;2>2;][C;2>2;]2)(:[C;2>2;]):[C;2>2;]

[O;2>2;]([C;3>3;]:1:[C]:[C]:[C]:[C]:[C]:1)[.>-][C;3>3;]([->.][N;2>1;][C;2>2;])([N;2>2;])=[N;2>2;]

[O;1>1;][.>-][C;2>2;]([->.][C;3>2;](:[C;2>2;]):[C;3>3;])[C;3>3;]

[S;1>1;][.>=][C;3>2;][:>.]1([:>.][N;2>1;][:>-][C;3>3;](:[C;2>2;]):[C;3>3;]([:>-][N;3>2;][:>.]1[C;1>1;]):[C;2>2;])[->=][N;2>2;][C;3>3;]

[O;2>2;]([C;4>4;]([C])([C])[C])[.>-][Cl;1>1;][->.][N;3>2;]([C;4>4;])[C;4>4;]

[C;1>1;][Si;4>4;]([C;1>1;])([C;1>1;])[.>-][N;2>2;]([->.][C;3>2;]([C;2>2;])[->=][C;2>2;][C;3>3;])=[N;2>2;+]

[C;2>2;]([C;3>3;]:1:[C]:[C]:[C]([O][C]):[C]:[C]:1)[.>-][N;2>3;](:[N;2>2;]):[N;2>2;]

In [6]:
difference_ba = list(set([cq for _, cq in b_q]) - set([cq for _, cq in a_q]))
print(len(difference_ba))
for r in difference_ba:
    r.clean2d()
    display(r)
    print(str(r))

14

[O;2>2;+]([O;1>1;-])[.>=][O;1>1;][=>.][C;2>2;]([.>=][C;3>3;]([C;1>1;])[C;1>1;])[C;2>2;]

[Cl;1>1;][.>-][C;3>3;]([C;3>3;])([C;1>1;])[->.][N;3>2;](:[N;2>2;]):[C;3>3;]

[C;1>1;][Si;4>4;]([C;1>1;])([C;1>1;])[.>-][N;2>2;]([->.][C;3>2;]([->=][C;2>2;][C;3>3;])[C;2>2;])=[N;2>2;+]

[C][S;4>4;]([O;2>2;][.>-][C;2>2;]([->.][N;3>2;]([C;2>2;])[C;1>1;])[C;2>2;])(=[O])=[O]

[Cl;1>1;][.>-][C;3>3;]([->.][N;3>2;](:[N;2>2;]):[C;2>2;])([C;4>4;])=[O;1>1;]

[N;2>2;][N;2>2;][->=][C;2>2;][C;3>3;]

[C;2>2;][C;2>2;][->=][C;3>3;]([C;2>2;])[C;2>2;]

[Cl;1>1;][.>-][C;3>3;]1([->.][N;3>2;]([C;2>2;])[C;3>3;]:[C;3>3;][N;3>2;]([C;3>3;])[->.][C;3>3;]([.>-][Cl;1>1;])([C;3>3;]1)=[O;1>1;])=[O;1>1;]

[Br;1>1;][.>-][C;3>3;](:[N;2>2;])(:[C;2>2;])[->.][S;4>3;]([C;1>1;])(=[O;1>1;])[=>-][O;1>1;0>-]

[C;2>2;][C;2>2;][->=][C;2>1;][->.][B;3>2;]([O;2>2;])[O;2>2;]

[O;2>2;]([C;3>3;]:1:[C]:[C]:[C]:[C]:[C]:1)[.>-][C;3>3;]([=>.][N;2>1;][C;2>2;])([N;2>2;])[->=][N;2>2;][C;2>2;]

[C;3>3;][C;3>2;][->.]1[->=][N;2>2;][C;3>3;]:[C;3>2;](:[C;2>2;])[->.][C;3>2;]([->=][O;1>1;])[C;4>3;][->.]1([C;1>1;])[C;1>1;]

[O;1>1;][.>=][C;2>2;]([->.][C;3>2;]([C;3>3;])[=>-][C;3>3;]([->=][O;1>1;])[C;2>2;])[C;3>3;]

[I;1>1;][.>-][C;2>2;]([->.][C;4>3;]([C;2>2;])([S;4>4;])[C;2>2;])[C;1>1;]

In [11]:
# A \ B as ReactionContainer
b_cq_set = {cq for _, cq in b_q}
difference_ab_rxn = [q for q, cq in a_q if cq not in b_cq_set]

# B \ A as ReactionContainer (optional)
a_cq_set = {cq for _, cq in a_q}
difference_ba_rxn = [q for q, cq in b_q if cq not in a_cq_set]

In [12]:
for r in difference_ab_rxn:
    r.clean2d()
    display(r)
    print(str(r))

[C;D2:1]-[N;D2:2]-[C;D3:4](-[N;D2:3])=[N;D2:5]>>[C;D2:1]-[N;D1:2].[N;D2:3]-[C;D3:4](=[N;D2:5])-[O;D2:6]-[C;D3:7]:1:[C:8]:[C:9]:[C:10]:[C:11]:[C:12]:1

[C;D2:1]:[C;D3:2]:1:[N;D2:3]:[C;D3:10](:[N;D3:5](:[C;D3:4]:1:[C;D2:7])-[C;D1:6])-[N;D2:9]-[C;D3:8]>>[C;D2:1]:[C;D3:2](-[N;D1:3]):[C;D3:4](-[N;D2:5]-[C;D1:6]):[C;D2:7].[C;D3:8]-[N;D2:9]=[C;D2:10]=[S;D1:11]

[C;D2:1]:[C;D3:2](:[C;D3:3])-[C;D2:5]-[C;D3:4]>>[C;D2:1]:[C;D2:2]:[C;D3:3].[C;D3:4]-[C;D2:5]-[O;D1:6]

[C;D3:2]-1(-[C;D3:3])-[C;D3:4]:[C;D3:5]-[C;D3:6](-[C;D3:7])-[C;D3:8]-1-[C;D3:9]-[O;D1:10]>>[O;D1:1]-[C;D4:2]-1(-[C;D3:3])-[C;D3:4]:[C;D3:5]-[C;D3:6](-[C;D3:7])=[C;D3:8]-1-[C;D3:9]-[O;D2:10]-[C;D2:11]-[C;D1:12]

[C;D3:1]-[C;D3:2]:1:[C;D2:4]:[C;D3:6](-[C;D3:5]):[N;D2:12]:[N;D2:11]:1>>[C;D3:1]-[C;D3:2](=[O;D1:3])-[C;D1:4].[C;D3:5]-[C;D3:6](-[O;D2:7]-[C;D2:8]-[C:9])=[O;D1:10].[N;D1:11]-[N;D1:12]

[C;D2:1]-[N;D3:2]-1-[C;D3:3]:[C;D3:4]-[N;D3:5](-[C;D3:6])-[C;D3:8](-[C;D3:7]-[C;D3:11]-1=[O;D1:13])=[O;D1:10]>>[C;D2:1]-[N;D2:2]-[C;D3:3]:[C;D3:4]-[N;D2:5]-[C;D3:6].[C;D3:7](-[C;D3:8](-[Cl;D1:9])=[O;D1:10])-[C;D3:11](-[Cl;D1:12])=[O;D1:13]

[N;D3:1]-1(-[C;D2:5]-[C;D2:6]-[N;D3:7](-[C;D3:2](:[C;D2:3]):[C;D2:4])-[C;D2:8]-[C;D2:9]-1)-[C;D3:11](:[C;D2:12]):[C;D2:13]>>[F;D1:10]-[C;D3:11](:[C;D2:12]):[C;D2:13].[N;D3:1]-1(-[C;D3:2](:[C;D2:3]):[C;D2:4])-[C;D2:5]-[C;D2:6]-[N;D2:7]-[C;D2:8]-[C;D2:9]-1

[N;D2:1]:[N;D2:2]:[N;D2:12]>>[N;D2:1]:[N;D3:2](-[C;D2:3]-[C;D3:4]:1:[C:5]:[C:6]:[C:7](-[O:8]-[C:9]):[C:10]:[C:11]:1):[N;D2:12]

[C;D3:1]-[O;D2:2]-[C;D3:3](=[O;D1:4])-[O;D2:15]>>[C;D3:1]-[O;D1:2].[C;D3:3](=[O;D1:4])(-[O;D2:5]-[C;D3:6]:1:[C:7]:[C:8]:[C:9](-[N+:10](-[O-:11])=[O:12]):[C:13]:[C:14]:1)-[O;D2:15]

[C;D3:1]-[C;D2:4]-[C;D3:3](-[C;D2:2])-[N;D2:5]=[N;D2+:6]>>[C;D3:1]-[C;D2:4]=[C;D2:3]-[C;D2:2].[N;D2:5](=[N;D2+:6])-[Si;D4:8](-[C;D1:7])(-[C;D1:9])-[C;D1:10]

[C;D4:1]-[N;D3:2](-[C;D4:3])-[Cl;D1:4]>>[C;D4:1]-[N;D2:2]-[C;D4:3].[Cl;D1:4]-[O;D2:5]-[C;D4:6](-[C:7])(-[C:8])-[C:9]

In [13]:
for r in difference_ba_rxn:
    r.clean2d()
    display(r)
    print(str(r))

[C;D3:1]-[C;D3:2](=[C;D3:3](-[O;D1:4])-[C;D2:5])-[C;D2:7]-[C;D3:6]>>[C;D3:1]-[C;D2:2]-[C;D3:3](=[O;D1:4])-[C;D2:5].[C;D3:6]-[C;D2:7]=[O;D1:8]

[N;D2:1]-[N;D2:2]-[C;D2:3]-[C;D3:4]>>[N;D2:1]-[N;D2:2]=[C;D2:3]-[C;D3:4]

[C;D2:1]-[C;D2:2]-[C;D3:3](-[C;D2:4])-[C;D2:5]>>[C;D2:1]-[C;D2:2]=[C;D3:3](-[C;D2:4])-[C;D2:5]

[C;D2:1]-[C;D2:2]-[C;D2:3]-[B;D3:5](-[O;D2:4])-[O;D2:6]>>[C;D2:1]-[C;D2:2]=[C;D1:3].[O;D2:4]-[B;D2:5]-[O;D2:6]

[C;D3:1]-[C;D3:2](-[C;D1:3])-[N;D3:5](:[N;D2:4]):[C;D3:6]>>[C;D3:1]-[C;D3:2](-[C;D1:3])-[Cl;D1:7].[N;D2:4]:[N;D2:5]:[C;D3:6]

[C;D2:1]-[N;D2:2]=[C;D3:4](-[N;D2:3])-[N;D2:5]-[C;D2:6]>>[C;D2:1]-[N;D1:2].[N;D2:3]-[C;D3:4](=[N;D2:5]-[C;D2:6])-[O;D2:7]-[C;D3:8]:1:[C:9]:[C:10]:[C:11]:[C:12]:[C:13]:1

[C;D3:1](:[N;D2:2])(:[C;D2:3])-[S;D4:5](-[C;D1:4])(=[O;D1:6])=[O;D1:7]>>[C;D1:4]-[S;D3:5](=[O;D1:6])-[O;D1-:7].[C;D3:1](:[N;D2:2])(:[C;D2:3])-[Br;D1:8]

[C;D2:1]-[N;D3:2]-1-[C;D3:3]:[C;D3:4]-[N;D3:5](-[C;D3:6])-[C;D3:11](-[C;D3:7]-[C;D3:8]-1=[O;D1:10])=[O;D1:13]>>[C;D2:1]-[N;D2:2]-[C;D3:3]:[C;D3:4]-[N;D2:5]-[C;D3:6].[C;D3:7](-[C;D3:8](-[Cl;D1:9])=[O;D1:10])-[C;D3:11](-[Cl;D1:12])=[O;D1:13]

[C;D3:1]-[C;D3:2]-1-[N;D2:3]-[C;D3:4]:[C;D3:6](:[C;D2:5])-[C;D3:7](-[O;D1:8])-[C;D4:9]-1(-[C;D1:10])-[C;D1:11]>>[C;D2:7](=[O;D1:8])-[C;D3:9](-[C;D1:10])-[C;D1:11].[C;D3:1]-[C;D2:2]=[N;D2:3]-[C;D3:4]:[C;D2:6]:[C;D2:5]

[C;D2:1]-[C;D4:2](-[S;D4:3])(-[C;D2:4])-[C;D2:5]-[C;D1:7]>>[C;D2:1]-[C;D3:2](-[S;D4:3])-[C;D2:4].[C;D2:5](-[I;D1:6])-[C;D1:7]

[C;D2:1]-[N;D3:2](-[C;D1:3])-[C;D2:7]-[C;D2:8]>>[C:4]-[S;D4:5](-[O;D2:6]-[C;D2:7]-[C;D2:8])(=[O:9])=[O:10].[C;D2:1]-[N;D2:2]-[C;D1:3]

[O;D1:1]=[C;D2:3]-[C;D2:2]>>[C;D2:2]-[C;D2:3]=[C;D3:6](-[C;D1:7])-[C;D1:8].[O;D1:1]=[O;D2+:4]-[O;D1-:5]

[N;D2:1]:[N;D3:2](:[C;D2:3])-[C;D3:4](-[C;D4:5])=[O;D1:6]>>[C;D3:4](-[C;D4:5])(=[O;D1:6])-[Cl;D1:7].[N;D2:1]:[N;D2:2]:[C;D2:3]

[C;D3:1]-[C;D2:2]-[C;D3:3](-[C;D2:4])-[N;D2:5]=[N;D2+:6]>>[C;D3:1]-[C;D2:2]=[C;D2:3]-[C;D2:4].[N;D2:5](=[N;D2+:6])-[Si;D4:8](-[C;D1:7])(-[C;D1:9])-[C;D1:10]

### Check by reaction indices if the unique rule in set A present in  set B

In [16]:
import pandas as pd

wa = pd.read_csv("../mapping/uspto_full_rules_light_pop_3_uu.tsv", sep="\t")
wb = pd.read_csv("../mapping/uspto_full_rules_light_pop_3_uuu.tsv", sep="\t")
wa.head()

,rule_smarts,popularity,reaction_indices
0,[C;D3:1]-[O;D1:2]>>[C;D3:1]-[O;D2:2]-[C;D1:3],19048,"385,483,3476,3478,800,2877,2887,2080,2468,3522..."
1,[C;D3:1]-[N;D1:2]>>[C;D3:1]-[N;D3+:2](-[O;D1-:...,18916,"3,198,238,250,251,361,380,403,3367,1720,1749,1..."
2,[C;D3:1]-[C;D3:2](=[O;D1:4])-[N;D2:6]-[C;D3:5]...,8633,"517,2084,2085,2086,2087,7580,14959,15281,15282..."
3,[C;D3:1]-[O;D1:2]>>[C;D3:1]-[O;D2:2]-[C;D2:3]-...,8631,"36,397,401,448,3139,1608,785,794,798,810,812,8..."
4,[C;D3:1]-[C;D3:2](=[O;D1:4])-[N;D2:5]-[C;D3:6]...,8125,"3290,3295,3297,3298,3303,3306,3308,1572,1583,1..."

In [65]:
qa_smarts = '[C;D3:1]-[O;D2:2]-[C;D3:3](=[O;D1:4])-[O;D2:15]>>[C;D3:3](=[O;D1:4])(-[O;D2:5]-[C;D3:6]:1:[C:7]:[C:8]:[C:9](-[N+:10](-[O-:11])=[O:12]):[C:13]:[C:14]:1)-[O;D2:15].[C;D3:1]-[O;D1:2]'
qa = smarts(qa_smarts)
qa.clean2d()
display(qa)
qwa = wa[wa.rule_smarts == qa_smarts]
qwa

,rule_smarts,popularity,reaction_indices
41414,[C;D3:1]-[O;D2:2]-[C;D3:3](=[O;D1:4])-[O;D2:15...,3,"695562,697164,858919"

In [66]:
# qwa.reaction_indices is like: '1013855,1013857,1014029'
target_ids = {x.strip() for x in qwa.iloc[0].reaction_indices.split(",") if x.strip()}

# wb.reaction_indices is also comma-separated strings
wb_hits = wb[
    wb["reaction_indices"]
    .fillna("")
    .astype(str)
    .str.split(",")
    .apply(lambda xs: any(x.strip() in target_ids for x in xs))
].copy()
wb_hits

Empty DataFrame
Columns: [rule_smarts, popularity, reaction_indices]
Index: []

In [67]:
qb = smarts(wb_hits.iloc[0].rule_smarts)
qb.clean2d()
qb

IndexError: single positional indexer is out-of-bounds

In [36]:
cgr_qa = ~qa
cgr_qa.clean2d()
cgr_qa

In [37]:
cgr_qb = ~qb
cgr_qb.clean2d()
cgr_qb

In [28]:
for a_rule, q_cgr in a_q:
    if a_rule.reactants[0] == xx:
        a_rule.clean2d()
        display(a_rule)
        q_cgr.clean2d()
        display(q_cgr)

In [23]:
list(a_cq_set)[0]

In [29]:
for b_rule, qb_cgr in b_q:
    if b_rule.reactants[0] == xx:
        b_rule.clean2d()
        display(b_rule)
        qb_cgr.clean2d()
        display(qb_cgr)